name: AGEViewer build

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Backend install and test
      run: cd backend && npm install && npm run test:ageParsing
    - name: Frontend install and build
      run: cd frontend && npm install && npm run build
      env:
        CI: false
        NODE_OPTIONS: --openssl-legacy-provider
